### ISSUE TITLE
Seems broken, as tested on http://plusfeed.frosas.net/

### ISSUE THREAD

**Issue by sycom** [frosas/google-plus-user-feed#17]
As of around April 20th 2018, http://plusfeed.frosas.net/ stopped delivering rss from any G+ account I was following. Older post are still displayed, but I guess they're cached? Probably a G+ evolution?

Sorry for not being more accurate on the bug report.

**Comment by frosas** [comment]
Thanks for reporting this, Sylvain.

The server disk was out of space and I was totally unaware of it!

I've freed up some space and feeds should appear updated now. Whenever I
have some more time I'll put some measures in place to avoid this to happen
again.

**Comment by sycom** [comment]
Glad to see the problem was not as hard I was expecting.  Google drives me paranoid with his war against RSS.

cheers.
