### ISSUE TITLE
error handling new lines? generating wrong characters (backspaces?) in the feed title

### ISSUE THREAD

**Issue by sycom** [frosas/google-plus-user-feed#8]
I just can guess the problem comes from a combination of "!" and "new line" or just some type of "new line" but in some case, the generated feed is not well formed : with two "BS" . You can see the result here, throwing a`XML parsing error: <unknown>:43:47: not well-formed (invalid token)` error : 

http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fplusfeed.frosas.net%2F111186574931872193621

the incriminated text is 

> <title>Du coté obscur du cacao!
> Un chocolatier de Rouen a réalisé cette superbe statue de Dark Vador, a…</title>

**Comment by sycom** [comment]
well, the <br> has been removed from the title so the feed changed. But double "BS" remains and the feed is still broken.

**Comment by frosas** [comment]
Thanks for reporting the bug @sycom, I'll look at it when I have a free moment!
